# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20161230_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageurl',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Cart'),
        ),
    ]
