# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_cartitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
