# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20161231_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='imageurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
